import = [
	"~/.config/alacritty/themes/themes/argonaut.toml"
]
[window]
	opacity = 0.8
	decorations = "Full"
	startup_mode = "Maximized"
	dynamic_title = true
	class = { instance = "Alacritty", general = "Alacritty" }
	dimensions = { columns = 100, lines = 30 }
[shell]
	program = "/bin/bash"
[font]
	normal = { family = "FiraCode Nerd Font", style = "mono" }
	bold = { family = "FiraCode Nerd Font", style = "mono" }
	italic = { family = "FiraCode Nerd Font", style = "mono" }
[terminal]
	osc52 = "CopyPaste"

