import = [
	"~/.config/alacritty/themes/themes/argonaut.toml"
]
[env]
TERM = "xterm-256color"
[colors]
draw_bold_text_with_bright_colors = true
[window]
	opacity = 0.8
	decorations = "None"
	startup_mode = "Maximized"
	dynamic_title = true
	class = { instance = "Alacritty", general = "Alacritty" }
	dimensions = { columns = 100, lines = 30 }
[shell]
	program = "/bin/bash"
[font]
	normal = { family = "FiraCode Nerd Font Ret", style = "Regular" }
	bold = { family = "FiraCode Nerd Font Mono SemBd", style = "Bold" }
	italic = { family = "FiraCode Nerd Font Mono Light", style = "Italic" }
[terminal]
	osc52 = "CopyPaste"

