# Cambiando el prefijo por defecto de Tmux (Ctrl + B)
set -g default-terminal screen-256color
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Instalador de plugins
set -g @plugin 'tmux-plugins/tpm'

# Plugins instalados
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin "wfxr/tmux-power"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "alexwforsythe/tmux-which-key"
set -g @plugin "tmux-plugins/tmux-cpu"

# Paleta de colores
GREY="#444444"
NORD0="#2e3440"
NORD1="#3b4252"
NORD2="#434c5e"
NORD4="#4c566a"
NORD8="#81A1C1"

# configuración de la barra de estado
set -g @tmux_power_theme "#81a1c1"
set -g @tmux_power_date_icon "󰃭"
set -g @tmux_power_date_format "%F"
set -g @tmux_power_time_icon '󰥔'
set -g @tmux_power_user_icon ''
set -g @tmux_power_session_icon ''
set -g @tmux_power_right_arrow_icon     ''
set -g @tmux_power_left_arrow_icon      ''
set -g @tmux_power_show_host false
set -g @tmux_power_show_user false

# Estilos propios
set -g status-style "bg=${NORD1}"
set -g status-position top
set -g status-justify absolute-centre

set -g status-right "#[bg=$NORD4,fg=$GREY]\ue0bc \
#[fg=$NORD8,bold]CPU:#{cpu_percentage} \
#[bg=$GREY,fg=$NORD4]\ue0bc\
#[bg=$NORD8,fg=$GREY,bold]\ue0bc \
\uf007 #H "

set -g status-left "#[bg=$NORD8,fg=$GREY,bold] \ueb79 \
#S \
#[fg=$NORD8,bg=$GREY]\ue0bc\
#[bg=$NORD4,fg=$GREY]\ue0bc \
#[fg=$NORD8]RAM:#{ram_percentage} \
#[bg=$GREY,fg=$NORD4]\ue0bc"

set-option -g status-left-length 100
set-option -g status-right-length 100

# Ventana activa
set-option -g window-status-current-format "\
#[fg=$NORD1,bg=$NORD8]\ue0bc\
#[bg=$NORD8,fg=$GREY,bold] #I\
:\
#W#{window_flags} \
#[fg=$NORD8,bg=$NORD1]\ue0bc "

# Ventana inactiva
set-option -g window-status-format "\
#[bg=$NORD4,fg=$GREY]\ue0bc\
#[fg=$NORD8,bg=$NORD4,bold] #I\
:\
#W#{window_flags} \
#[fg=$NORD4,bg=$GREY]\ue0bc"

set-option -g window-status-separator ""

# Dividir el panel en vertical
unbind %
bind | split-window -h -c "#{pane_current_path}"

# Dividir el panel en horizontal
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Limpiar terminal
bind L send-keys 'C-l'

# Índices de los paneles se inician en 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Recargar la configuración de Tmux
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# movimiento en los páneles de tmux
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

set-window-option -g mode-keys vi

# reescalar los páneles con el mouse
bind -r m resize-pane -Z

set-option -g default-shell "/bin/zsh"

# Habilitar el mouse
set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
